def all_clans():
	return {
		'Legendary Monks':'#PCCUPG9R',
		# 'SN JAIN':'#2029V92QV',
		# 'Brute Force':'#22PQL2L0R',
		# 'PBfPN':'#22QL8YUC8',
		# 'Wookies':'#298092P99',
		# 'Mini Matter':'#2PJYCQYV9',
		# 'Endor':'#2YLL8UVPY',
		# 'Mos Eisley':'#2YUVPQQCU',
		# 'Killer_Black_Wf':'#8VQYR2LR',
		'Golden Clan':'#C2QPR82Q',
		# 'Optimus Prime*':'#JR8CQRR',
		'PETARUNG SEJATI':'#PCP02V8C',
		'Dark Matter':'#Q2VYY8C8',
		# 'barudak sunda':'#RRJ02JGC',
		'Sheer Force':'#VUCVG2J0',
		# 'UnitedAsOne':'#YVPVGPP2',
		'ReqReceiveN WAR':'#J2PVJ2GU',
		'ONE KINGS':'#P9C8YJRQ',
		'Clash of War':'#C200RPVV',
		'We Are Trying':'#29CC8Y98R',
		'Mini Matter':'#2PJYCQYV9',
	}
